[package]
name = "tf_roslibrust"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "BSD 3-Clause"
publish = false
description = """
This is a rust port of the [ROS tf library](http://wiki.ros.org/tf).
It is intended for being used in robots to help keep track of multiple coordinate
frames and is part of a larger suite of rust libraries that provide support for
various robotics related functionality.
This supports ROS1 using the roslibrust crate.
"""

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
nalgebra.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.5.1"
smart-default = "0.7.1"
thiserror.workspace = true
tokio = "1.38.0"

[dependencies.roslibrust]
# git = "https://github.com/Carter12s/roslibrust.git"
# branch = "master"
version = "0.10.2"
# rev = "a1eb5a875906a26aa172a7465dd018858d191665"
# branch = "time_ops"
features = ["ros1"]

[dependencies.roslibrust_codegen]
# git = "https://github.com/Carter12s/roslibrust.git"
# branch = "master"
version = "0.10"
# rev = "a1eb5a875906a26aa172a7465dd018858d191665"
# branch = "time_ops"

[dependencies.roslibrust_codegen_macro]
# git = "https://github.com/Carter12s/roslibrust.git"
# branch = "master"
version = "0.10"
# git = "https://github.com/lucasw/roslibrust.git"
# rev = "a1eb5a875906a26aa172a7465dd018858d191665"
# branch = "time_ops"
